global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'auth-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8000']
    metrics_path: '/metrics'

  - job_name: 'user-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8001']
    metrics_path: '/metrics'

  - job_name: 'appointment-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8002']
    metrics_path: '/metrics'

  - job_name: 'notification-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8003']
    metrics_path: '/metrics'

  - job_name: 'mqtt-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8004']
    metrics_path: '/metrics'

  - job_name: 'metrics-service'
    static_configs:
      - targets: ['${SERVICES_HOST}:8005']
    metrics_path: '/metrics'

  - job_name: 'node-exporter'
    static_configs:
      - targets: ['${SERVICES_HOST}:9100']
